services:
  api:
    build:
      context: ./
    ports:
      - "18080:18080"
      - "18081:18081"
      - "4026:4026"
    volumes:
      - ./https:/https:ro
    working_dir: /src/Prosigliere.Challenge.WebApi
    command:
      [
        "dotnet", "watch", "run",
        "--urls", "http://0.0.0.0:18080;https://0.0.0.0:18081",
        "--launch-profile", "Docker"
      ]
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    depends_on:
      - sqlserver
    networks:
      - challenge-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "DH9sd98daDSD987"
      ACCEPT_EULA: "Y"
    ports:
      - "11433:1433"
    networks:
      - challenge-net

  test:
    build:
      context: ./
    volumes:
      - ./https:/https:ro
    working_dir: /src/Prosigliere.Challenge.Tests
    command: ["dotnet", "test", "--logger:trx"]
    networks:
      - challenge-net

networks:
  challenge-net: